// Shared verified content for three visual prototypes; quote previews never send customer data.
const icons = {
  shield: '<path d="m12 3 8 3v6c0 5-8 9-8 9s-8-4-8-9V6l8-3Z"/><path d="m8 12 3 3 5-6"/>',
  shine: '<path d="m12 3 2.5 6.5L21 12l-6.5 2.5L12 21l-2.5-6.5L3 12l6.5-2.5L12 3Z"/>',
  drop: '<path d="M12 3S5 11 5 15a7 7 0 0 0 14 0c0-4-7-12-7-12Z"/><path d="M9 15a3 3 0 0 0 3 3"/>',
  layers: '<path d="m12 3 10 5-10 5L2 8l10-5Z"/><path d="m2 12 10 5 10-5M2 16l10 5 10-5"/>'
};
const icon = name => `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.4" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${icons[name]}</svg>`;
window.UI = {
  button: (label = 'Claim the $599 offer', href = '#quote') => `<a class="button" href="${href}">${label}<span aria-hidden="true">↗</span></a>`,
  header: () => `<header class="site-header container"><a class="brand" href="#" aria-label="Super Shine Auto Detailing home"><img src="assets/logo.webp" alt="" width="54" height="54"><span>SUPER SHINE<small>AUTO DETAILING</small></span></a><nav class="desktop-nav" aria-label="Main navigation"><a href="#benefits">The protection</a><a href="#portfolio">Our work</a><a href="#why">Why Super Shine</a></nav><a class="header-call" href="tel:+17752207064"><span class="phone-symbol" aria-hidden="true">↗</span> (775) 220-7064</a><button class="menu-toggle" type="button" aria-expanded="false" aria-controls="mobile-menu">Menu <span aria-hidden="true">☰</span></button><nav id="mobile-menu" hidden aria-label="Mobile navigation"><a href="#benefits">The protection</a><a href="#portfolio">Our work</a><a href="#why">Why Super Shine</a><a href="#quote">Get a free quote</a><a href="tel:+17752207064">(775) 220-7064</a></nav></header>`,
  benefits: () => `<section id="benefits" class="section container"><div class="section-heading"><span class="eyebrow">MORE THAN A BEAUTIFUL FINISH</span><h2>A little science.<br>A whole lot of shine.</h2><p>Ceramic coating is a liquid polymer that bonds with your paint. Nanotechnology fills microscopic surface pores, creating a durable, hydrophobic layer that makes everyday care easier.</p></div><div class="benefit-grid">${[
    ['shield','Long-lasting paint protection','A durable shield against UV rays, oxidation, bird droppings, sap, and light scratches.'],
    ['shine','Deep gloss. Mirror finish.','A rich, wet-look shine that brings out your paint’s depth and color, long after the detail.'],
    ['drop','Water beads. Dirt leaves.','Hydrophobic protection helps water, dirt, and grime slide off, making washes easier and faster.'],
    ['layers','An extra layer of defense','Scratch and chemical resistance helps minimize swirl marks and environmental damage.']
  ].map(([i,title,text]) => `<article class="benefit"><div class="benefit-icon">${icon(i)}</div><h3>${title}</h3><p>${text}</p></article>`).join('')}</div><p class="fine-print">Ceramic coating is not scratch-proof or a substitute for paint protection film. Proper care still matters.</p></section>`,
  why: () => `<section id="why" class="section container"><div class="section-heading"><span class="eyebrow">THE SUPER SHINE STANDARD</span><h2>Your car deserves<br>people who care.</h2><p>Your local ceramic coating specialists in Stockton, California. Honest work. Real attention to detail.</p></div><div class="why-grid">${[
    ['Up to 10-year warranty','Long-lasting durability to keep your vehicle glossy and protected. Ask us about coverage and care requirements.'],
    ['Highly trained. Multi-certified.','Experienced professionals certified in advanced ceramic coating applications.'],
    ['Your time, respected.','Convenient, reliable service with a commitment to delivering on time.'],
    ['100+ satisfied customers','Trusted by local drivers for results, service, and a 4.9 Google rating.'],
    ['100% honest work','Transparent pricing, no hidden charges, and integrity in every job.']
  ].map(([title,text],i)=>`<article class="reason"><span class="reason-number">0${i+1}</span><h3>${title}</h3><p>${text}</p></article>`).join('')}</div></section>`,
  portfolio: () => `<section id="portfolio" class="section container"><div class="section-heading"><span class="eyebrow">THE FINISH SPEAKS FOR ITSELF</span><h2>Real cars.<br>Super shine.</h2><p>A closer look at the completed projects featured in our portfolio.</p></div><div class="portfolio-grid">${[['charger','Turquoise Dodge Charger','Color that comes alive'],['project-2','Super Shine completed vehicle project','Every detail, considered'],['project-3','Vehicle from the Super Shine portfolio','A finish worth a second look'],['project-4','Super Shine automotive detailing project','The Super Shine standard']].map(([file,alt,caption],i)=>`<figure><img src="assets/${file}.webp" alt="${alt}" loading="lazy" width="900" height="1125"><figcaption><span>${caption}</span><span>0${i+1} ↗</span></figcaption></figure>`).join('')}</div><a class="text-link" href="https://www.instagram.com/supershineauto_detailing/" target="_blank" rel="noopener noreferrer">More from the shop on Instagram <span aria-hidden="true">↗</span></a></section>`,
  quote: () => `<section id="quote" class="section container"><div class="quote-layout"><div class="quote-copy"><span class="eyebrow">YOUR NEXT GREAT FIRST IMPRESSION</span><h2>Let's make your<br>car shine.</h2><p>Get a free quote for our premium 10-year ceramic coating offer. Tell us a little about your vehicle.</p><div class="quote-price"><strong>$599</strong><span><s>$1,200</s><small>Limited-time offer</small></span></div><p>Up to a 10-year warranty. Confirm offer eligibility, vehicle preparation, and warranty terms with the shop.</p><a class="text-link" href="tel:+17752207064">Prefer a conversation? (775) 220-7064 ↗</a></div><form class="quote-form"><span class="form-kicker">YOUR FREE QUOTE STARTS HERE</span><label>Full name <span aria-hidden="true">*</span><input name="name" autocomplete="name" placeholder="Your full name" required maxlength="100"></label><label>Phone number <span aria-hidden="true">*</span><input name="phone" type="tel" autocomplete="tel" placeholder="(555) 123-4567" required pattern="[+0-9 .\\(\\)\\-]{7,25}" maxlength="25" title="Enter a phone number using 7–25 digits, spaces, or phone punctuation."></label><label>Car details <span aria-hidden="true">*</span><input name="vehicle" placeholder="Year, make & model" required maxlength="160"></label><button class="button" type="submit">Preview my free quote request <span aria-hidden="true">↗</span></button><p class="form-note">Design preview only. Nothing is sent or saved. To request a real quote, <a href="https://supershinedetailing.automarktninja.com/ceramic-coating" target="_blank" rel="noopener noreferrer">use the live website</a> or call the shop.</p><p class="form-status" role="status" tabindex="-1" hidden></p></form></div></section>`,
  faq: () => `<section id="faq" class="section container"><div class="section-heading"><span class="eyebrow">GOOD QUESTIONS. STRAIGHT ANSWERS.</span><h2>Before your car<br>gets the spotlight.</h2></div><div class="faq-list"><details><summary>What is the current ceramic coating offer?</summary><p>The source offer is premium 10-year ceramic coating for $599, normally $1,200, for a limited time. Contact the shop to confirm availability and what your vehicle needs.</p></details><details><summary>What does “up to a 10-year warranty” mean?</summary><p>The advertised coating offers up to 10 years of warranty and durability. Ask Super Shine about the specific coverage, eligibility, and maintenance requirements for your vehicle before booking.</p></details><details><summary>Will ceramic coating prevent every scratch?</summary><p>No. It helps resist light scratches, swirl marks, chemicals, and environmental contamination, but it is not scratch-proof. Ask about paint protection film (PPF) for a different level of physical protection.</p></details><details><summary>Where is Super Shine Auto Detailing?</summary><p>Visit us at 2735 Teepee Dr, Stockton, CA 95205, United States. Call <a href="tel:+17752207064">(775) 220-7064</a> to discuss your vehicle.</p></details></div></section>`,
  footer: () => `<footer class="site-footer"><div class="container footer-grid"><div><a class="brand" href="#"><img src="assets/logo.webp" alt="Super Shine logo" width="64" height="64"><span>SUPER SHINE<small>AUTO DETAILING</small></span></a><p>Ceramic coating. Paint protection.<br>Auto detailing. PPF. And a little obsession.</p></div><div><span class="eyebrow">COME BY THE SHOP</span><address>2735 Teepee Dr<br>Stockton, CA 95205, United States</address><a class="text-link" href="https://www.google.com/maps/search/?api=1&query=Super+Shine+Auto+Detailing+2735+Teepee+Dr+Stockton+CA+95205" target="_blank" rel="noopener noreferrer">Get directions ↗</a></div><div><span class="eyebrow">LET'S TALK DETAILS</span><a class="footer-phone" href="tel:+17752207064">(775) 220-7064</a><a class="text-link" href="https://www.instagram.com/supershineauto_detailing/" target="_blank" rel="noopener noreferrer">Instagram ↗</a><a class="text-link" href="#quote">Get a free quote ↗</a></div></div><div class="container footer-bottom"><span>© ${new Date().getFullYear()} Super Shine Auto Detailing</span><span>Independent design prototype · Not a live booking page</span></div></footer>`
};
